### ISSUE TITLE
[Feature request] use undocumented dark win32 theme

### ISSUE THREAD

**Issue by x-0D** [MishaProductions/Rectify11Installer#115]
I think it will be more compartability if mica dark will use undocumented win32 dark theming feature or high contrast theme as base.

at least using high contrast as base will fix some bugs with chromium, which uses win32 color pallete by default in some websites. sometimes it looks awful, because, as example, text bg is win32:white but text is hardcoded #000000.

Feature-related links:
https://github.com/ysc3839/win32-darkmode
https://blog.xojo.com/2021/11/18/welcome-to-the-dark-side-of-windows/

P.S: when release? i wanna install rectify 11 on fresh installed system.

**Comment by ojask** [comment]
alr, thanks for the suggestion, I will see what I can do.

**Comment by rounk-ctrl** [comment]
this would require to hook into every app, so no
