### ISSUE TITLE
Some Bugs needs Polishing and Improvement.

### ISSUE THREAD

**Issue by Vipin2003** [MishaProductions/Rectify11Installer#116]
### Description

There are some bugs which are not matching the Dark Theme are :
1. The Dark Theme is not applied correctly on some system apps and 3rd Party Apps like Regedit.
2.  The Text is not Visible in Dark Theme (see the ss). This is making problem in reading version in Adobe Info Page.
3. The winver is not applying the dark properly.
![2023-03-10_19h17_52](https://user-images.githubusercontent.com/93650504/224332407-126b2e92-ae2c-4f4c-a0d6-32e114c76482.jpg)
![2023-03-10_19h18_13](https://user-images.githubusercontent.com/93650504/224332417-d65f170d-184d-4dff-a1e1-de6f4b188401.jpg)
![2023-03-10_19h22_42](https://user-images.githubusercontent.com/93650504/224333447-28e52af1-96db-4db1-90dd-838c56501d35.jpg)

### Steps To Reproduce

1. Just Apply any Rectify Dark Theme and Start Regedit.
2. Open the Adobe Info in Application while in Rectify Dark.

### Rectify11 Version

v3.0 Preview 3

### Windows Version

Win11 22H2 22621.1344

### Logs

I don't know how to take this. Sorry.

**Comment by SmirbYrneh420** [comment]
1. Try using secureuxtheme
2. Adobe probably hardcoded white, try solution for 1 first. It that doesn’t work, it is impossible to fix
3. Reinstall rectify11

**Comment by Vipin2003** [comment]
1. I used to change it from secureuxtheme. (Not win default)
2. It was showing correctly when using some other dark theme. Only happening with rectify dark. One thing I forgot to mention is that on Rectify Dark, the ms excel workspace is also dark. Looking wierd.
3. For this, I have to reinstall windows.

**Comment by truffle-yt** [comment]
For the theme Try reapplying / restarting the pc (secureux seems to bug out sometimes)
> the ms excel workspace is also dark. Looking wierd.

For that you need a addon from github to fix it due to how excel takes msstyles
