### ISSUE TITLE
Make a AME Wizard Playbook

### ISSUE THREAD

**Issue by TaylorGit32** [MishaProductions/Rectify11Installer#141]
Don't know if this is possible, But maybe make a Playbook for a easier install?

AME Wizard Site : Research purposes 
https://ameliorated.io/

#

**Comment by rounk-ctrl** [comment]
❌

**Comment by Typical0** [comment]
> Don't know if this is possible, But maybe make a Playbook for a easier install?
> 
> AME Wizard Site : Research purposes https://ameliorated.io/

This option was considered earlier, but for now, we don't plan to have a Playbook for Rectify11.
