### ISSUE TITLE
Error 0 when installing runtimes with lastest nightly build

### ISSUE THREAD

**Issue by CivilizedGuide** [MishaProductions/Rectify11Installer#144]
On the most recent nightly build there is an error when installing runtimes where vcredist.exe and core31.exe return error code 0 and the program crashes. With [https://github.com/MishaProductions/Rectify11Installer/actions/runs/4897670139](url) this doesn't happen.
I'm using tiny11 if that's an issue 

(Sorry idk how to mention actions)

**Comment by Thisisauser6443** [comment]
Have a bash at the latest commit (2592f4d) from the actions tab - Worked for me, so it's worth a shot
