### ISSUE TITLE
Control Center Not installed

### ISSUE THREAD

**Issue by aa1386** [MishaProductions/Rectify11Installer#147]
### Description

Hi.so i just installed rectify and 1. the control center no matter what i do i cant install it and the 2. is that in some apps like Control Panel some places of it are dark and some other places are white . Thanks

### Steps To Reproduce

.

### Rectify11 Version

3.0

### Windows Version

Windows 11 Pro,22H2,22623.1325

### Logs

![Screenshot 2023-05-16 173811](https://github.com/MishaProductions/Rectify11Installer/assets/96339406/63996954-02b5-4b47-b622-b02937651884)

**Comment by natesworks** [comment]
i had the same thing

**Comment by Akitakek** [comment]
Mine looks completely fine using the latest GitHub actions build.

![image](https://github.com/MishaProductions/Rectify11Installer/assets/7873528/7728ff35-ed12-4c5e-a0a1-81dfa691c84c)

Would be able to help you better if you gave steps to reproduce.
Aka which exact build of Rectify did you use, what options you have on/off, etc..

**Comment by Typical0** [comment]
1. What's the exact version of v3.0 you're all installing?
2. We are aware of the control panel issue. It was fixed long time ago.
3. Control Center is compiled and bundled with Rectify11. There's no way to download it manually.

**Comment by lalit22km** [comment]
> 

Fixed the issue. I used the build from the release page and I believe @aa1386 is using the same. Upon reading @Akitakek comment I downloaded the latest build from the Actions build. It's working now. Issue can be closed now I guess.

**Comment by khalil-anas-github** [comment]
hey, how to get the rectify11 control panel, I can't get it. Thanks

**Comment by lalit22km** [comment]
> hey, how to get the rectify11 control panel, I can't get it. Thanks

You have to download the latest Actions build. Here's the link if you can't find it.

https://github.com/MishaProductions/Rectify11Installer/suites/12874577167/artifacts/694489904

**Comment by dariomadeira** [comment]
Same here. it didn't install Mica For Everyone and the control panel, I download lastest windows 11 ISO from Microsoft and install it, next install rectify and i have that problem. @lalit22km your link is not working, Thanks!

**Comment by khalil-anas-github** [comment]
> Same here. it didn't install Mica For Everyone and the control panel, I download lastest windows 11 ISO from Microsoft and install it, next install rectify and i have that problem. @lalit22km your link is not working, Thanks!

hey, the link was not working for me too but when I connected back to github it worked

**Comment by NightRain86** [comment]
> > hey, how to get the rectify11 control panel, I can't get it. Thanks
> 
> You have to download the latest Actions build. Here's the link if you can't find it.
> 
> https://github.com/MishaProductions/Rectify11Installer/suites/12874577167/artifacts/694489904

Thank You. This worked for me
