### ISSUE TITLE
Flow Launcher Transparent Background Broken

### ISSUE THREAD

**Issue by Today20092** [MishaProductions/Rectify11Installer#148]
### Description

Flow launcher's transparent background does not work with any of the available settings with rectify11 including

- title bar color:  system, light, dark
- backdrop type: default, none, mica, acrylic, tabbed
- corner modes: default/square/rounded/slightly rounded

### Steps To Reproduce

1. Install [rectify11](https://github.com/MishaProductions/Rectify11Installer/actions/runs/4967246567)
2. Change settings to default
3. Open flow launcher

### Rectify11 Version

Rectify11 "Disable Signing" Action

### Windows Version

10.0.22621 Build 22621

### Logs

# [Flow Launcher ](https://www.flowlauncher.com/)Transparency Broken
![](https://i.imgur.com/cdtD13e.png)
The outline around the box should not be visible
## Rectify11 Settings:
![image](https://github.com/MishaProductions/Rectify11Installer/assets/79241611/434971b3-82c9-4516-a843-9e8afce53afb)

## Flow Launcher Settings: 
![](https://i.imgur.com/063uM38.png)

**Comment by Akitakek** [comment]
Can confirm the "Query window shadow effect" is broken.
Depending on other settings it'll be fully opaque or invisible.

**Comment by SmirbYrneh420** [comment]
this is a micaforeveryone issue, not a rectify11 issue

pls reserve these issues for mfe repo

**Comment by Today20092** [comment]
> this is a micaforeveryone issue, not a rectify11 issue
> 
> pls reserve these issues for mfe repo
