### ISSUE TITLE
Uninstaller doesn't work

### ISSUE THREAD

**Issue by iWixii** [MishaProductions/Rectify11Installer#149]
### Description

Uninstaller doesn't work...

### Steps To Reproduce

run the installer
click on uninstall button
doesn't work

### Rectify11 Version

3.0.0.0

### Windows Version

Windows 11 Pro 22H2 22621.1702

### Logs

-

**Comment by xverge** [comment]
This is already tracked in #99

**Comment by Vipin2003** [comment]
It is also not working in 3.0.35.0...It asks for the things you want to uninstall, but after clicking next, It won't work.

**Comment by itsarian** [comment]
> 

at least it got one step further
