### ISSUE TITLE
Installer pages changeable with arrow keys and mouse buttons

### ISSUE THREAD

**Issue by xverge** [MishaProductions/Rectify11Installer#151]
### Description

The pages of the installer can be moved through using arrow keys and mouse side buttons, which if done before installation started, breaks the installer but otherwise allows to move through the pages and change the installation

### Steps To Reproduce

1. Launch the installer
2. Move through the pages with arrow keys and mouse side buttons 

### Rectify11 Version

Commit 2592f4d5f

### Windows Version

Windows 10 22H2

### Logs

Image from @DVT#3460
![image](https://github.com/MishaProductions/Rectify11Installer/assets/118953668/c68132d2-6f41-435d-b3ba-1ff0f41bd7d4)

**Comment by rounk-ctrl** [comment]
fixed ig in latest commit
