### ISSUE TITLE
Control panel not properly consistent

### ISSUE THREAD

**Issue by ItsDragonaire** [MishaProductions/Rectify11Installer#153]
I have tried everything on the web tried uninstalling and reinstalling
tried repairing everything
but nothing seems to fix this issue
the sidebar and the menubar of the ctrl panel are still inconsistent and mica isn't working

[Doc1.docx](https://github.com/MishaProductions/Rectify11Installer/files/11523983/Doc1.docx)

**Comment by xverge** [comment]
Are you using the Release Preview?

**Comment by SmirbYrneh420** [comment]
Did you use the nightly GitHub actions build?

Or did you use RP3?

Either way, I suggest reinstalling Rectify 11.

NOTE: BEFORE RE-RUNNING THE APP, PLEASE DELETE THE RECTIFY11 FOLDER IN C:\WINDOWS\

**Comment by evansidhu** [comment]
Same, to fix mica, use the micaforeveryone app

**Comment by MishaProductions** [comment]
You need to patch shell32 i think

**Comment by Plasman888** [comment]
> You need to patch shell32 i think

How do you do that?
