### ISSUE TITLE
How to set Default theme SQL Server 2019

### ISSUE THREAD

**Issue by mrreddevil2412** [MishaProductions/Rectify11Installer#155]
<img width="624" alt="image" src="https://github.com/MishaProductions/Rectify11Installer/assets/30259651/d893b1dc-d80b-4e75-9326-ed4ea2b508ed">

**Comment by SmirbYrneh420** [comment]
Unfortunately, this can not be easily fixed. Is there a theme setting in SQL Server? If not, then unfortunately they hard-coded colors in this software, which cannot be fixed

**Comment by mrreddevil2412** [comment]
> Unfortunately, this can not be easily fixed. Is there a theme setting in SQL Server? If not, then unfortunately they hard-coded colors in this software, which cannot be fixed

Thanks you!
Currently I am using all default SQL configuration
