### ISSUE TITLE
Stuck on replacing files due to nvcontainer (NEWBIE)

### ISSUE THREAD

**Issue by DarkSuffer** [MishaProductions/Rectify11Installer#157]
![image](https://github.com/MishaProductions/Rectify11Installer/assets/102059805/a5a2c899-2a4b-4b1f-ae89-85a5aa8660b1)
How can I fix this? I need help please

**Comment by evansidhu** [comment]
Have you tried reinstalling, if that does not work them maybe try some cmd commands like sfc /scannow or dism /online /cleanup-image /restorehealth, also is this the release preview or the nightly action build, if it is the release preview, you should switch to the nightly build as it is more fluent in my opinion, but please note that the nightly build will be much less stable than the release preview, create a restore point before installing and after that start the process and enjoy the eye candy.

**Comment by MishaProductions** [comment]
Can you please provide more details? What happens if you press ok?

**Comment by DarkSuffer** [comment]
> Can you please provide more details? What happens if you press ok?

It will appear again in a matter of minutes

**Comment by DarkSuffer** [comment]
And what do you recommend to install Recify version if you're in Windows 10? rp2 or rp3? I'm new to this so I don't understand any of those

**Comment by DarkSuffer** [comment]
I only wanted icons, But I added extra so I think that's the issue which Nvidia appeared

**Comment by evansidhu** [comment]
You should not install it on windows 10, there is a reason why it is rectify11 and not rectify10

**Comment by MishaProductions** [comment]
This isn't a rectify11 issue, its an issue with your graphics drivers.
