### ISSUE TITLE
BLACK BACGROUND IN EXPLORER NOT THE MICA ONE

### ISSUE THREAD

**Issue by wildgamharsh** [MishaProductions/Rectify11Installer#160]
### Description

i installed the latest rectify 11 and i selected the dark with mica option and now in file explorer the background is super black and the top is mica which looks worse than before please help me 

### Steps To Reproduce

Please do implement the mica in explorer

### Rectify11 Version

V3 RP3

### Windows Version

Windows 11 22H2

### Logs

Get the dark background in explorer fixed

**Comment by SmirbYrneh420** [comment]
is micaforeveryone installed? is explorerframe installed and running?

**Comment by SmirbYrneh420** [comment]
go to task scheduler and look for a task called exploderframe. then tell me if it is running or if it quit unexpectedly

**Comment by onlysunnythakur** [comment]
Start menu shortcut not shown

**Comment by onlysunnythakur** [comment]
and gadegts are not shown

**Comment by Typical0** [comment]
MicaForEveryone isn't implemented in RP3.

**Comment by xPhoenix07** [comment]
i installed mica one but the background is all black and after the instalation and reboot i didn't get any mica related thing running in on task manager and i also didn't got the rectify controlls thing in my all apps menu

**Comment by wildgamharsh** [comment]
I FOUND THE SOLUTION THANKS

**Comment by DeZenTID** [comment]
> I FOUND THE SOLUTION THANKS

what's the solution???

**Comment by RTFTR** [comment]
> > I FOUND THE SOLUTION THANKS
> 
> what's the solution???

You need Explorerframe to fix it

**Comment by DeZenTID** [comment]
> > > I FOUND THE SOLUTION THANKS
> > 
> > 
> > what's the solution???
> 
> You need Explorerframe to fix it

That worked, thank you very much.
I put it on the startup folder and it worked flawlessly.
