### ISSUE TITLE
Display Color Calibration Program has broken colors in Dark Mode (dccw.exe)

### ISSUE THREAD

**Issue by Abdulhadi5692HDI2** [MishaProductions/Rectify11Installer#164]
### Description

The Display Color Calibration Program has broken colors in the rectified Dark Mode.

### Steps To Reproduce

Open the Display Color Calibration Program

### Rectify11 Version

3.0.35.0

### Windows Version

Windows 11 22H2 22621.1778

### Logs

![Screenshot 2023-06-01 145655](https://github.com/MishaProductions/Rectify11Installer/assets/110974220/e1578527-280f-4de2-915d-b2c298810f52)

**Comment by SmirbYrneh420** [comment]
could be hardcoded colors in windows, idk if this can be fixed

**Comment by Abdulhadi5692HDI2** [comment]
oh
