### ISSUE TITLE
Double messagebox asking to close is back

### ISSUE THREAD

**Issue by Vichingo455** [MishaProductions/Rectify11Installer#165]
### Description

Well it's annoying

### Steps To Reproduce

1. Open installer and select install
2. Hit the close button

### Rectify11 Version

Latest

### Windows Version

Windows 11 22H2

### Logs

No logs

**Comment by Vichingo455** [comment]
That issue was also mentioned in #65 but never fixed

**Comment by rounk-ctrl** [comment]
https://github.com/MishaProductions/Rectify11Installer/assets/70931017/30b835fc-1736-46fc-bf01-42c0b1b2bfbc

its fixed
