### ISSUE TITLE
second monitor is flashing

### ISSUE THREAD

**Issue by aniel300** [MishaProductions/Rectify11Installer#166]
### Description

second monitor is flashing after applying this

### Steps To Reproduce

it is just happening

### Rectify11 Version

rp3

### Windows Version

latest windows insider

### Logs

n/a

**Comment by ItsRedlyXD** [comment]
Have you tried the latest github actions build?

**Comment by aniel300** [comment]
yes

**Comment by MishaProductions** [comment]
Not related to rectify11

**Comment by aniel300** [comment]
yes i believe this is or was cause but a new gpu driver
