### ISSUE TITLE
Cannot be uninstalled

### ISSUE THREAD

**Issue by justin45669874** [MishaProductions/Rectify11Installer#169]
### Description

Well, I was trying to uninstall Rectify11 but when I click uninstall, it does nothing like there wasn't anything in that button.
This is what it looks like when click it:
![image](https://github.com/MishaProductions/Rectify11Installer/assets/51263008/83641040-31fa-439b-bb21-3c54005a7310)

### Steps To Reproduce

1. Open Control Panel
2. Find Rectify11 and click Uninstall
3. Click Uninstall Rectify11

### Rectify11 Version

3.0.0.0

### Windows Version

Windows 11 22H2 22621.1778

### Logs

It's neither unhandled exception nor phase2 bug. It was the uninstallation bug.
![image](https://github.com/MishaProductions/Rectify11Installer/assets/51263008/e6c5fe1f-6577-4ec3-8cf4-e16adbd19139)

**Comment by HolyNetworkAdapter** [comment]
Uninstaller is incomplete

**Comment by buihuy2301** [comment]
please complete uninstall feature soon. what is program release without uninstall? at least pin it into readme.md or give we a tutorial to get rid of this thing.

**Comment by Typical0** [comment]
Duplicate of https://github.com/MishaProductions/Rectify11Installer/issues/99 https://github.com/MishaProductions/Rectify11Installer/issues/94 https://github.com/MishaProductions/Rectify11Installer/issues/89 https://github.com/MishaProductions/Rectify11Installer/issues/71 https://github.com/MishaProductions/Rectify11Installer/issues/71 https://github.com/MishaProductions/Rectify11Installer/issues/149 https://github.com/MishaProductions/Rectify11Installer/issues/158

**Comment by rounk-ctrl** [comment]
use the latest action build if you want uninstaller

**Comment by user4302** [comment]
> use the latest action build if you want uninstaller

where can i find that?
