### ISSUE TITLE
SECUREUXHELPER.exe VIRUS

### ISSUE THREAD

**Issue by djekanovic** [MishaProductions/Rectify11Installer#171]
### Description

After installing this i got the file above: SECUREUXHELPER.exe  in my windows folder. 

Here is what virustotal haves to say, Malwarebytes too:

ALYac
Generic.DoubleAgent.0ED2E1AC
Antiy-AVL
Trojan/Win32.SGeneric
Arcabit
Generic.DoubleAgent.0ED2E1AC
BitDefender
Generic.DoubleAgent.0ED2E1AC
Cybereason
Malicious.c0781d
Cylance
Unsafe
Cynet
Malicious (score: 100)
Cyren
W64/ABRisk.JXDP-8996
DeepInstinct
MALICIOUS
Elastic
Malicious (moderate Confidence)
Emsisoft
Generic.DoubleAgent.0ED2E1AC (B)
eScan
Generic.DoubleAgent.0ED2E1AC
Fortinet
Malicious_Behavior.SB
GData
Generic.DoubleAgent.0ED2E1AC
Google
Detected
Gridinsoft (no cloud)
Trojan.Win64.Agent.cl
Malwarebytes
Malware.AI.4226720291
MAX
Malware (ai Score=85)
MaxSecure
Trojan.Malware.205864674.susgen
McAfee
Artemis!2386FC3C0781
McAfee-GW-Edition
BehavesLike.Win64.BadFile.qm
QuickHeal
Trojan.Agent
Rising
Trojan.Generic@AI.98 (RDML:jW2KDDG5Oj9JE/I83JQWSw)
Sangfor Engine Zero
Trojan.Win32.Agent.Vu2s
Sophos
Mal/Generic-S
Trellix (FireEye)
Generic.DoubleAgent.0ED2E1AC
TrendMicro-HouseCall
TROJ_GEN.R002H09A223
VIPRE
Generic.DoubleAgent.0ED2E1AC
Webroot
W32.Malware.Gen
Acronis (Static ML)
Undetected

https://www.virustotal.com/gui/file/bbabd6a0f7e54780f870a8519c8ef5896065cd9b1be850dfd804f39449d85087

### Steps To Reproduce

Install it.

### Rectify11 Version

latest

### Windows Version

Latest

### Logs

....

**Comment by Typical0** [comment]
Please ignore this. SexureUxHelper has been known to be detected as a false positive.

**Comment by userdev265scratchandpython** [comment]
thanks for the help!
