### ISSUE TITLE
Bug in 'Control Panel'

### ISSUE THREAD

**Issue by quan201200298** [MishaProductions/Rectify11Installer#180]
### Description

Its a bug in Control Panel 
And also, I cant uninstall Rectify11...

### Steps To Reproduce

I just ran sfc /scannow but it didnt work

### Rectify11 Version

Version 3.0

### Windows Version

Windows 11 21H2 22000.2124

### Logs

![image](https://github.com/MishaProductions/Rectify11Installer/assets/86346116/3e80e3b0-3a77-462c-901c-fdb20209c6c4)
![image](https://github.com/MishaProductions/Rectify11Installer/assets/86346116/8ca9d92d-0679-4c3f-85c1-16bd35295e9f)

**Comment by YT-Advanced** [comment]
Reinstall Rectify11 may fix it
![image](https://github.com/MishaProductions/Rectify11Installer/assets/70064328/ef71b649-a156-4fc2-ad83-6fdb2f9f912e)

**Comment by quan201200298** [comment]
![image](https://github.com/MishaProductions/Rectify11Installer/assets/86346116/3fe540f4-732d-4e81-ab42-093c61cdd040)
what about word =.=
