### ISSUE TITLE
Bug in ms paint

### ISSUE THREAD

**Issue by loadstring1** [MishaProductions/Rectify11Installer#183]
### Description

I installed recitify 11 (dark mode with mica for everyone) and mspaint is light mode! Please help me fix it.

### Steps To Reproduce

Install recitify 11 (dark mode with mica for everyone)
open mspaint
and it will be flash your eyes with light instead of darkmode (changing mspaint to dark mode with mica for everyone is also barely working)

### Rectify11 Version

https://github.com/MishaProductions/Rectify11Installer/actions/runs/5409600584 (im using this one)

### Windows Version

Windows 11 22H2 (tiny 11 + recitify 11, 22621.1194)

### Logs

![Zrzut ekranu (1525)](https://github.com/MishaProductions/Rectify11Installer/assets/97308997/3b5c58ce-0aa0-43cb-a2fb-d693e277fa6f)

**Comment by legofanlovessayori** [comment]
not a problem with rectify11, use windhawk to enable dark mode paint since microsoft have made a dark variant but its not accessable

**Comment by loadstring1** [comment]
still it would be cool if recitify 11 changed that by default so you dont need to install third party apps just to change paint theme to dark mode

**Comment by TechnoEggnog** [comment]
iirc Dev and Canary insider channels do have the update with Paint dark mode, not stable yet though last I checked

**Comment by Vipin2003** [comment]
Just install this one which supports dark mode officially.

[Microsoft.Paint_11.2304.18.0.zip](https://github.com/MishaProductions/Rectify11Installer/files/12016802/Microsoft.Paint_11.2304.18.0.zip)
(change extension from .zip to .msixbundle)
