### ISSUE TITLE
MS may be trying to sneak into users' computers.

### ISSUE THREAD

**Issue by PandaChen1** [MishaProductions/Rectify11Installer#184]
When you install Windows 11 with a PC without TPM and UEFI, the PC will be monitored by MS and the motherboard will be destroyed.

Some people's computers can be repaired by downgrading Windows 10, some people's computers can be restored by cleaning up NVRAM, and some old computers have their Southbridge burned out.
But we don't know the specifics. However, we learned that computers were indeed destroyed, and without exception, all of them were old computers with Windows 11 installed, none of which did meet the standards of Windows 11

But strangely, there are also some people's old computers because they have TPM modules (1.2 or 2.0) and also have UEFI, so they are not broken

At the moment, I only have this information, and I have doubts about this for the time being. To protect victims, I will not publish their contact details here.

What are your thoughts on this matter?

**Comment by TechnoEggnog** [comment]
my brother in Ra, this is not at all related to Rectify11

**Comment by travy-patty** [comment]
skill issue this isnt related to r11

**Comment by PandaChen1** [comment]
> 技能问题 这与 R11 无关

Has Rectify11 had this issue?

**Comment by PandaChen1** [comment]
> skill issue this isnt related to r11

Has Rectify11 had this issue?

**Comment by PandaChen1** [comment]
> skill issue this isnt related to r11

Did Rectify11 have this feedback before this?

**Comment by TechnoEggnog** [comment]
this isn’t really an issue r11 even deals with, take your source-less argument elsewhere
