### ISSUE TITLE
Release time of v3

### ISSUE THREAD

**Issue by Leonardo5681** [MishaProductions/Rectify11Installer#185]
I've been waiting months for the release of the new version of rectify11 because I don't want to put a release preview, so when does it come out?

**Comment by SirEthanator** [comment]
Just use the latest actions build for now. They are pretty stable.

**Comment by MishaProductions** [comment]
It will release whenever the uninstaller is finished

**Comment by Bennett-Fourr** [comment]
if someone installed now will they be able to use the uninstaller when it is finished
